name: testlab
description: A comprehensive Flutter testing learning module demonstrating unit, widget, and integration tests.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.1 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.24.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true

