include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Prefer const constructors
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
    
    # Prefer final fields
    prefer_final_fields: true
    prefer_final_locals: true
    
    # Avoid unnecessary containers
    avoid_unnecessary_containers: true
    
    # Prefer sized box over container for sizing
    sized_box_for_whitespace: true
    
    # Prefer relative imports
    prefer_relative_imports: true
    
    # Avoid empty catch blocks
    avoid_empty_else: true
    
    # Prefer single quotes
    prefer_single_quotes: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
