name: my_profile_app
description: A Personal Profile App demonstrating Flutter widgets and Material 3 design.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.1 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/avatar.png
